# Generated by Django 6.0.1 on 2026-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
