# Generated by Django 6.0.1 on 2026-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
