# Generated by Django 6.0.1 on 2026-01-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_alter_target_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='status',
            new_name='completed',
        ),
    ]
