# Generated by Django 6.0.1 on 2026-01-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_cat'),
        ('targets', '0004_rename_status_target_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='missions.mission'),
        ),
    ]
