# Generated by Django 6.0.1 on 2026-01-12 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifier of the gas station shift', primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('cat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mission', to='cats.cat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
