# Generated by Django 6.0.1 on 2026-01-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='status',
            new_name='completed',
        ),
    ]
