# Generated by Django 6.0.1 on 2026-01-12 15:23

import cats.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifier of the gas station shift', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('expirience', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('breed', models.CharField(max_length=100, validators=[cats.validators.validate_breed])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
